/*
 * generated by Xtext
 */
package com.cburch.logisim.statemachine.validation

import org.eclipse.xtext.validation.Check
import com.cburch.logisim.statemachine.fSMDSL.Command
import com.cburch.logisim.statemachine.fSMDSL.PortRef
import com.cburch.logisim.statemachine.fSMDSL.InputPort
import com.cburch.logisim.statemachine.fSMDSL.OutputPort

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class FSMDSLValidator extends AbstractFSMDSLValidator {

//  public static val INVALID_NAME = 'invalidName'
//
	@Check
	def checkCommand(Command c) {
		c.name instanceof OutputPort &&
		c.value.eAllContents.filter(PortRef).forall[ref|ref.port instanceof InputPort]
		
	}
}
