/*
 * generated by Xtext
 */
package com.cburch.logisim.statemachine.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.cburch.logisim.statemachine.services.FSMDSLGrammarAccess;

public class FSMDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FSMDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.cburch.logisim.statemachine.parser.antlr.internal.InternalFSMDSLParser createParser(XtextTokenStream stream) {
		return new com.cburch.logisim.statemachine.parser.antlr.internal.InternalFSMDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TOP";
	}
	
	public FSMDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FSMDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
